export const skills = [
  "react.svg",
  "nextjs.svg",
  "js.svg",
  "html.svg",
  "css.svg",
  "nodejs.svg",
  "express.svg",
  "python.svg",
  "bootstrap.svg",
  "git.svg",
  "github.svg",
  "mongodb.svg",
  "tailwind.svg",
];
